#!/bin/bash

echo "🚀 Deploying Garment POS to Render..."

echo "📋 Instructions for Render Deployment:"
echo ""
echo "1. Go to https://render.com"
echo "2. Create a free account"
echo "3. Click 'New +' and select 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Use these settings:"
echo ""
echo "   Name: garment-pos-backend"
echo "   Environment: Node"
echo "   Build Command: cd backend && npm install"
echo "   Start Command: cd backend && npm start"
echo "   Plan: Free"
echo ""
echo "6. Add these Environment Variables:"
echo "   NODE_ENV=production"
echo "   PORT=10000"
echo "   JWT_SECRET=your-super-secret-jwt-key-here"
echo "   JWT_EXPIRES_IN=24h"
echo ""
echo "7. Click 'Create Web Service'"
echo ""
echo "8. Your backend will be deployed to:"
echo "   https://garment-pos-backend.onrender.com"
echo ""
echo "9. For the frontend, create another Web Service:"
echo "   Name: garment-pos-frontend"
echo "   Build Command: cd frontend && npm install && npm run build"
echo "   Start Command: cd frontend && npm start"
echo "   Environment Variable: NEXT_PUBLIC_API_URL=https://garment-pos-backend.onrender.com/api"
echo ""
echo "🎉 Your Garment POS will be live at:"
echo "   Backend: https://garment-pos-backend.onrender.com"
echo "   Frontend: https://garment-pos-frontend.onrender.com"
echo "   Health Check: https://garment-pos-backend.onrender.com/health"
