#!/bin/bash

echo "🚀 Deploying Backend to Render..."
echo ""
echo "📋 Follow these exact steps:"
echo ""
echo "1. Go to https://render.com and login"
echo "2. Click 'New +' and select 'Web Service'"
echo "3. Connect your GitHub repository (if not already connected)"
echo "4. Use these exact settings:"
echo ""
echo "   🔧 Service Settings:"
echo "   - Name: garment-pos-backend"
echo "   - Environment: Node"
echo "   - Region: Choose closest to you"
echo "   - Branch: main (or your default branch)"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install"
echo "   - Start Command: npm start"
echo "   - Plan: Free"
echo ""
echo "   🔑 Environment Variables (add these):"
echo "   - NODE_ENV = production"
echo "   - PORT = 10000"
echo "   - JWT_SECRET = your-super-secret-jwt-key-here-change-in-production"
echo "   - JWT_EXPIRES_IN = 24h"
echo "   - DATABASE_URL = (we'll add this later)"
echo ""
echo "5. Click 'Create Web Service'"
echo ""
echo "6. Your backend will be deployed to:"
echo "   https://garment-pos-backend.onrender.com"
echo ""
echo "7. Once deployed, update your frontend API URL:"
echo "   NEXT_PUBLIC_API_URL = https://garment-pos-backend.onrender.com/api"
echo ""
echo "🎉 Your Garment POS Backend will be live!"
echo "🔗 Health Check: https://garment-pos-backend.onrender.com/health"
